# -*- coding: utf-8 -*-
"""05_sales_kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilayzRlNcpPCEZiYM18eC0yb0h4L2XhM
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import warnings
from sklearn.preprocessing import StandardScaler
warnings.filterwarnings('ignore')

df = pd.read_csv("sales_data_sample.csv", encoding="latin")

df.head()

df.info()

df = df[['ORDERLINENUMBER', 'SALES']]

scaler = StandardScaler()
scaled_values = scaler.fit_transform(df.values)

wcss = []
for i in range(1, 11):
    model = KMeans(n_clusters=i, init='k-means++')
    model.fit_predict(scaled_values)
    wcss.append(model.inertia_)

plt.plot(range(1, 11), wcss, 'ro-')
plt.show()

model = KMeans(n_clusters=7, init='k-means++')
clusters = model.fit_predict(scaled_values)
clusters

df['cluster'] = clusters

df

df.describe()

model.inertia_

plt.scatter(df['ORDERLINENUMBER'], df['SALES'], c=df['cluster'])
plt.title('K-Means Clustering on Sales Data')
plt.xlabel('Order Line Number')
plt.ylabel('Sales')
plt.show()


# What is K-Means clustering? Explain the algorithm briefly.

# A: K-Means clustering is an unsupervised machine learning algorithm used to partition a dataset into K distinct clusters. It works by randomly initializing K centroids, assigning data points to the nearest centroid, and then updating the centroids based on the mean of the assigned points. This process repeats until convergence, typically defined as no significant change in centroids.
# Q: How do you determine the optimal number of clusters in K-Means?

# A: The optimal number of clusters can be determined using the Elbow Method, which involves plotting the inertia (sum of squared distances from each point to its assigned centroid) against the number of clusters. The point where the inertia starts to decrease at a slower rate indicates the optimal number of clusters, forming an "elbow" in the plot.
# Q: What is hierarchical clustering and how does it differ from K-Means?

# A: Hierarchical clustering is another clustering method that builds a hierarchy of clusters either in an agglomerative (bottom-up) or divisive (top-down) manner. Unlike K-Means, which requires the number of clusters to be specified beforehand, hierarchical clustering creates a dendrogram that allows exploration of different clusterings at various levels of granularity.
# Q: What are the advantages and disadvantages of K-Means clustering?

# A: Advantages of K-Means include simplicity, scalability, and speed. Disadvantages include the requirement to specify the number of clusters, sensitivity to outliers, and the possibility of converging to local minima.
# Q: Why is it essential to preprocess the data before applying clustering algorithms?

# A: Preprocessing is crucial because clustering algorithms are sensitive to the scale and distribution of the data. Normalizing or standardizing the data ensures that all features contribute equally to the distance calculations used in clustering, improving the algorithm's performance and the validity of the resulting clusters.

# xplain the significance of inertia in K-Means.

# A: Inertia is the sum of squared distances between data points and their respective cluster centers. It measures how tightly the clusters are packed. Lower inertia values indicate more compact clusters, which typically suggest better clustering.
# Q: What are the limitations of K-Means?

# A: K-Means may perform poorly with non-spherical clusters, outliers, and varying densities. It also requires pre-specifying the number of clusters (k), and its results can be affected by initial cluster center choices.
# Q: Why do we plot a heatmap of correlations before clustering?

# A: The correlation heatmap helps in identifying relationships between variables. Highly correlated variables may contribute redundant information, affecting clustering outcomes.
